version: "3.9"

services:
  profile-service:
    container_name: profile-service
    build: .
    env_file:
      - /home/deploy/config/.env.common
      - .env.staging
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4002/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    ports:
      - "4002:4002"
    restart: always
    networks:
      - gateway_app-net

networks:
  gateway_app-net:
    external: true
